### ISSUE TITLE
Laravel 5.2?

### ISSUE THREAD

**Issue by Mattnmoore** [analogueorm/laravel-auth#7]
Is this package compatible with Laravel 5.2? 

I am getting this error when trying to authenticate a user:

`InvalidArgumentException with message 'Authentication user provider [analogue] is not defined.'`

Here is my `config/auth.php`

```
<?php

return [

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],


    'providers' => [
        'users' => [
            'driver' => 'analogue',
            'model' => Analogue\LaravelAuth\User::class
        ],
    ],

];

```

Thanks!

**Comment by RemiCollin** [comment]
It hasn't been tested against L5.2 yet. However the message suggest that the package wouldn't be registered. Did you add Analogue\LaravelAuth\AnalogueAuthServiceProvider::class to your config/app.php ?

**Comment by tabennett** [comment]
In L5.2, `extend` was replaced with `provider`:
https://laravel.com/docs/5.1/authentication#adding-custom-authentication-drivers
https://laravel.com/docs/5.2/authentication#adding-custom-user-providers

You'll probably need to write your own method in the `App\Providers\AuthServiceProvider` if you want it to work (but you should be able to just copy/paste some the code from this package for most of it) . I'm gonna play around with this tonight and see if I can get Auth working in 5.2.

**Comment by RemiCollin** [comment]
@tabennett yes indeed, and so is the config file. i'll fix this asap, should only be a few tweaks.

**Comment by RemiCollin** [comment]
okay, had a deeper look. we can't just override the eloquent driver anymore, as it's hardcoded in https://github.com/laravel/framework/blob/5.2/src/Illuminate/Auth/CreatesUserProviders.php, will have to write a specific UserProvider, for Analogue.

**Comment by tabennett** [comment]
I don't think you're using that trait though are you? https://github.com/analogueorm/laravel-auth/blob/5.2/src/AnalogueUserProvider.php implements `Illuminate\Contracts\Auth\UserProvider`, but doesn't seem to be relying on that Trait anywhere. Also, I'm pretty sure that contract/interface hasn't changed from L5.1 -> L5.2. I was able to get this working on a fresh install of L5.2 like this:

1) Install the package using composer.
2) Instead of adding the `Analogue\LaravelAuth\AnalogueAuthServiceProvider` to config/app.php, I just wrote a small custom registration inside app/Providers/AuthServiceProvider (inside the boot method):

``` php
$this->app['auth']->provider('analogue', function($app) {
            return new AnalogueUserProvider (
                $app['Illuminate\Contracts\Hashing\Hasher'],
                $app['analogue'],
                $app['config']['auth.providers.users.model']
            );
        });
```

My `config/auth.php` providers array looks like this (I put my entities inside App\Entities):

``` php
'providers' => [
        'users' => [
            'driver' => 'analogue',
            'model'  => App\Entities\User::class,
        ],

        // 'users' => [
        //     'driver' => 'eloquent',
        //     'model' => App\User::class,
        // ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```

I would suggest that perhaps this package shouldn't provide an actual implementation of the user provider registration (because they vary between L5.1 and L5.2) but instead maybe just provide them with a snippet of code in the docs (as part of the installation of this package) that works for the version of Laravel that they're using.

**Comment by RemiCollin** [comment]
Ok seems simpler than I thought. There's no problem at all with providing an actual implementation as this package is maintained into several branches (5.0 , 5.1, 5.2) each one implementing for the corresponding laravel version, so updating it to work with 5.2 won't break the 5.1 version.

**Comment by RemiCollin** [comment]
I updated the package to use new extension mechanism. Now config should look like this : 

``` php
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'analogue',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'analogue',
        ],
    ],


    'providers' => [

...

        'analogue' => [
            'driver' => 'analogue',
            'model' => Analogue\LaravelAuth\User::class,
        ],

```

Not tested yet.

**Comment by RemiCollin** [comment]
Added a simple integration test, now everything should be working out of the box.
